### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by yoosuf** [reliefsupports/reliefsupports.org-v1#66] opened 2017-05-29 06:05 UTC
Its better allow language support like Tamil and English.

**Comment by ssudaraka** [comment] 2017-05-29 06:50
Similar issue: https://github.com/reliefsupports/reliefsupports.org/issues/1

**Comment by danishka** [comment] 2017-05-30 00:49
appreciate someone can contribute Tamil l10n.

**Comment by danishka** [comment] 2017-05-30 00:50
closing this as a duplicate of #1

**Closed as completed** 2017-05-30 00:51 UTC
Labels: Duplicate, Wontfix
